version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ReactiveProperty
    versions:
    - 7.7.0
    - 7.7.1
    - 7.8.0
    - 7.8.1
    - 7.8.2
    - 7.8.3
    - 7.9.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
